[package]
name = "system76-power"
version = "1.0.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[dependencies]
dbus = "=0.6.2"
libc = "0.2"
clap = "2.32.0"
log = "0.4.5"
fern = "0.5.6"
serde = "1.0.78"
serde_derive = "1.0.78"
toml = "0.4.6"
xdg = "2.1.0"
intel-pstate = "0.1.1"
sysfs-class = { git = "https://github.com/pop-os/sysfs-class", branch = "extra-derives" }

[build-dependencies]
vergen = "0.1.1"
